microblog/models/photo.py
import datetime
from microblog.extensions import db
from microblog.helpers import render_uri


class PhotoAlbum(db.Model):
    __tablename__ = 'photo_album'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), nullable=False)
    description = db.Column(db.Text)
    people_id = db.Column(db.Integer, db.ForeignKey('people.id', ondelete='CASCADE'))

    photos = db.relationship('Photo', backref=db.backref('album'), lazy='dynamic')
    people = db.relationship('People', backref=db.backref('albums', lazy='dynamic'))

    def __init__(self, title, people_id, description=None):
        self.title = title
        self.people_id = people_id
        self.description = description


class Photo(db.Model):
    __tablename__ = 'photo'
    id = db.Column(db.Integer, primary_key=True)
    uri = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)
    create_time = db.Column(db.DateTime, default=datetime.datetime.now)
    album_id = db.Column(db.Integer, db.ForeignKey('photo_album.id', ondelete='SET NULL'))
    people_id = db.Column(db.Integer, db.ForeignKey('people.id', ondelete='CASCADE'))

    people = db.relationship('People')

    def __init__(self, uri, people_id, description=None, album_id=None):
        self.uri = uri
        self.description = description
        self.album_id = album_id
        self.people_id = people_id

    def get_uri(self):
        return render_uri(self.uri)

#
#class VoiceAlbum(db.Model):
#    __tablename__ = 'voice_album'
#
#    id = db.Column(db.Integer, primary_key=True)
#    title = db.Column(db.String(80), nullable=False)
#    description = db.Column(db.Text)
#    people_id = db.Column(db.Integer, db.ForeignKey('people.id', ondelete='CASECADE'))


#class Voice(db.Model):
#    __tablename__ = 'voice'
#    id = db.Column(db.Integer, primary_key=True)
#    uri = db.Column(db.String(255))
#    description = db.Column(db.Text)
#    create_time = db.Column(db.DateTime, default=datetime.datetime.now)
#    album_id = db.Column(db.Integer)

microblog/forms/photo.py
# -*- coding: utf-8 -*-
from flask.ext.wtf import Form
from wtforms import TextAreaField, SubmitField, FileField, TextField, SelectField
from wtforms.validators import DataRequired, NoneOf


class UploadForm(Form):
    album = SelectField(u'相册')
    photo_1 = FileField(u'图片1')
    photo_2 = FileField(u'图片2')
    photo_3 = FileField(u'图片3')
    photo_4 = FileField(u'图片4')
    photo_5 = FileField(u'图片5')
    submit = SubmitField(u'上传')


class AddAlbumForm(Form):
    title = TextField(
        u'相册名称',
        validators=[DataRequired(message=u'请输入相册名称'), NoneOf([u'默认相册'], message=u'相册名称不合法')]
    )
    description = TextAreaField(u'相册描述')
    submit = SubmitField(u'新建')


class ModifyAlbumForm(AddAlbumForm):
    submit = SubmitField(u'修改')


class PhotoForm(Form):
    description = TextAreaField(u'照片描述')
    submit = SubmitField(u'修改')

microblog/views/photo.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os
from flask import Blueprint, flash, redirect, url_for, request, g, current_app, \
    abort
from flask.ext.login import login_required
from sqlalchemy import and_
from microblog.forms.photo import PhotoForm
from microblog.models import PhotoAlbum
from microblog.extensions import db
from microblog.forms import UploadForm, ModifyAlbumForm, AddAlbumForm
from microblog.helpers import get_uploader, render_template
from microblog.models import Photo


photo = Blueprint('photo', __name__, url_prefix='')


@photo.route('/album/add/', methods=['GET', 'POST'])
@login_required
def add_album():
    """新建相册"""
    add_album_form = AddAlbumForm()
    if add_album_form.validate_on_submit():
        album = PhotoAlbum(
            title=add_album_form.title.data,
            description=add_album_form.description.data,
            people_id=g.user.id
        )
        db.session.add(album)
        db.session.commit()
        flash('相册新建成功', 'success')
        return redirect(url_for('show_album', id=album.id))
        # return '添加成功'

    return render_template(
        'photo/album-info.html',
        form=add_album_form,
        title='新建相册'
    )


@photo.route('/album/<int:id>/')
@login_required
def show_album(id):
    """显示相册里的所有照片，只能查看自己的相册"""
    album = PhotoAlbum.query.get_or_404(id)
    #if album.people_id != g.user.id:
    #    flash('权限不足', 'warning')
    #    return redirect(url_for('frontend.index'))
    return render_template(
        'photo/album.html',
        album=album,
        title='查看相册'
    )


@photo.route('/album/<int:id>/modify/', methods=['GET', 'POST'])
@login_required
def modify_album(id):
    """修改相册属性"""
    album = PhotoAlbum.query.get_or_404(id)
    if album.people_id != g.user.id:
        flash('权限不足', 'warning')
        return redirect(url_for('show_album', id=album.id))
    if album.title == '默认相册':
        flash('无法修改属性', 'warning')
        return redirect(url_for('show_album', id=album.id))
    modify_album_form = ModifyAlbumForm(obj=album)
    if modify_album_form.validate_on_submit():
        album.title = modify_album_form.title.data
        album.description = modify_album_form.description.data

        db.session.add(album)
        db.session.commit()
        flash('相册修改成功', 'success')
        return redirect(url_for('show_album', id=album.id))

    return render_template(
        'photo/album-info.html',
        form=modify_album_form,
        title='修改相册属性'
    )


@photo.route('/album/<int:id>/delete/')
@login_required
def delete_album(id):
    """删除相册"""
    clear_album = request.args.get('clear')
    print clear_album
    album = PhotoAlbum.query.get_or_404(id)

    if album.people_id != g.user.id:
        flash('删除失败', 'warning')
        return redirect(url_for('frontend.album', id=g.user.id))
    if album.title == '默认相册':
        flash('无法删除默认相册', 'warning')
        return redirect(url_for('frontend.album', id=g.user.id))

    if clear_album == '1':
        # 删除相册内的照片
        print 'delete photos'
        for photo in album.photos:
            db.session.delete(photo)
            db.session.commit()
    else:
        # 移入默认相册
        # TODO: commit 需要重新考虑
        default_album = PhotoAlbum.query.filter_by(title='默认相册').first()
        if not default_album:
            # 如果没有默认相册，则新建一个默认相册
            default_album = PhotoAlbum(
                title='默认相册',
                people_id=g.user.id
            )
            db.session.add(default_album)
            db.session.commit()
        for photo in album.photos:
            photo.album_id = default_album.id
            db.session.add(photo)
            db.session.commit()

    db.session.delete(album)
    db.session.commit()
    flash('删除成功', 'success')
    return redirect(url_for('frontend.album', id=g.user.id))


@photo.route('/album/upload/', methods=['GET', 'POST'])
@photo.route('/album/<int:id>/upload/', methods=['GET', 'POST'])
@login_required
def upload_photo(id=None):
    if id:
        album = PhotoAlbum.query.get_or_404(id)
        if album.people_id != g.user.id:
            flash('权限不足', 'warning')
            return redirect('frontend.index')
    # 列出所有相册
    album_choices = [(str(a.id), a.title) for a in g.user.albums]
    if not album_choices:
        # 如果没有任何相册，则新建一个默认相册
        default_album = PhotoAlbum(
            title='默认相册',
            people_id=g.user.id
        )
        db.session.add(default_album)
        db.session.commit()
        album_choices.append((str(default_album.id), default_album.title))
        
    upload_form = UploadForm()
    upload_form.album.choices = album_choices
    if not id:
        id = album_choices[0][0]    # 第一个相册的 id
    upload_form.album.data = str(id)
    
    if upload_form.validate_on_submit():
        print 'id:', upload_form.album.data
        album = PhotoAlbum.query.get_or_404(upload_form.album.data)
        if album.people_id != g.user.id:
            flash('权限不足', 'warning')
            return redirect('frontend.index')
         # 循环上传照片
        for field in upload_form:
            print field.name
            if 'photo' in field.name and field.data:
                photo_data = request.files[field.name]
                uploader = get_uploader()
                filename = uploader.save(photo_data)
                if not filename:
                    flash('上传失败', 'danger')
                    return redirect(url_for('frontend.album', id=g.user.id))
                print upload_form.album.data
                photo = Photo(uri=filename, album_id=upload_form.album.data, people_id=g.user.id)
                db.session.add(photo)
                db.session.commit()
        flash('上传成功', 'success')
        return redirect(url_for('frontend.album', id=g.user.id))

    return render_template(
        'photo/upload.html',
        form=upload_form,
        title='上传照片'
    )


@photo.route('/photo/<int:pid>/')
@photo.route('/album/<int:aid>/photo/<int:pid>/')
def show_photo(pid, aid=None):
    photo = Photo.query.get_or_404(pid)
    prev_id = next_id = None
    if aid:
        if photo.album_id != aid:
            abort(404)
        else:
            # 获取 prev_id & next_id
            # 上一张和下一张
            prev_photo = Photo.query.filter(and_(Photo.id<pid, Photo.album_id==aid)).order_by(Photo.id.desc()).first()
            if prev_photo:
                prev_id = prev_photo.id
            next_photo = Photo.query.filter(and_(Photo.id>pid, Photo.album_id==aid)).first()
            if next_photo:
                next_id = next_photo.id
    return render_template(
        'photo/photo.html',
        photo=photo,
        prev_id=prev_id,
        next_id=next_id,
        title='查看照片'
    )


@photo.route('/photo/<int:id>/modify/', methods=['GET', 'POST'])
@login_required
def modify_photo(id):
    photo = Photo.query.get_or_404(id)
    if photo.people_id != g.user.id:
        flash('权限不足', 'warning')
        return redirect(url_for('frontend.index'))
    photo_form = PhotoForm(obj=photo)
    if photo_form.validate_on_submit():
        photo.description = photo_form.description.data
        db.session.add(photo)
        db.session.commit()
        flash('修改成功', 'success')
        return redirect(url_for('show_photo', id=id))
    return render_template(
        'photo/photo-info.html',
        form=photo_form,
        title='修改照片属性'
    )


@photo.route('/photo/<int:id>/delete/')
@login_required
def delete_photo(id):
    """删除照片"""
    photo = Photo.query.get_or_404(id)
    if photo.people_id != g.user.id:
        flash('删除失败', 'warning')
        return redirect(url_for('show_photo', id=id))
    print photo.uri
    uploader = get_uploader()
    uploader.remove(photo.uri)

    db.session.delete(photo)
    db.session.commit()
    flash('删除成功', 'success')
    if photo.album_id:
        return redirect(url_for('photo.show_album', id=photo.album_id))
    else:
        return redirect(url_for('frontend.album', id=g.user.id))


@photo.route('/photo/<int:pid>/move/<int:aid>/')
@login_required
def move_to_album(pid, aid):
    pass


@photo.route('/photo/<int:pid>/comment/')
@photo.route('/photo/<int:pid>/comment/<int:cid>/')
@login_required
def comment_photo(pid, cid):
    pass


@photo.route('/photo/comment/<int:id>/delete/')
@login_required
def delete_comment(id):
    pass

microblog/themes/newstyle/templates/photo/add-album.html
{% extends theme('layout.html') %}
{% set active = 'profile' %}
{% block title %}相册 | {{ title }}{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-3">
            {{ img_avatar(g.user) }}
            <hr />
        </div>
        <div class="col-lg-9">
            <form class="form-horizontal" role="form" action="" method="POST">

                <div class="form-group">
                    {{ form.title.label(class_='col-lg-2 control-label') }}
                    <div class="col-lg-6">
                        {{ form.title(class_='form-control') }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form.description.label(class_='col-lg-2 control-label') }}
                    <div class="col-lg-6">
                        {{ form.description(class_='form-control', rows=6) }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-6">
                        {{ form.submit(class_='btn btn-primary') }}
                    </div>
                </div>
                {{ form.hidden_tag() }}

            </form>
        </div>
    </div>
</div>
{% endblock %}

microblog/themes/newstyle/templates/photo/album-info.html
{% extends theme('layout.html') %}
{% set active = 'album' %}
{% block title %}相册 | {{ title }}{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-3">
            {{ img_avatar(g.user) }}
            <hr />
        </div>
        <div class="col-lg-9">
            <form class="form-horizontal" role="form" action="" method="POST">

                <div class="form-group">
                    {{ form.title.label(class_='col-lg-2 control-label') }}
                    <div class="col-lg-6">
                        {{ form.title(class_='form-control') }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form.description.label(class_='col-lg-2 control-label') }}
                    <div class="col-lg-6">
                        {{ form.description(class_='form-control', rows=6) }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-6">
                        {{ form.submit(class_='btn btn-primary') }}
                    </div>
                </div>
                {{ form.hidden_tag() }}

            </form>
        </div>
    </div>
</div>
{% endblock %}

microblog/themes/newstyle/templates/photo/album.html
{% extends theme('layout.html') %}
{% set active = 'album' %}
{% block title %}相册 | {{ title }}{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-3">
            {{ img_avatar(album.people) }}
            <h4 class="text-center">{{ album.people.nickname }}</h4>
            <hr />
        </div>
        <div class="col-lg-9">
            <h2>{{ album.title }}</h2>
            {% if album.description %}
            <p class="text-muted">{{ album.description }}</p>
            {% endif %}
            <hr />
            {% for photo in album.photos %}
            {% if loop.index0 % 4 == 0 %}
            <div class="row">
            {% endif %}
                <div class="col-lg-3">
                    <a href="{{ url_for('photo.show_photo', pid=photo.id, aid=photo.album_id) }}" class="thumbnail">
                        <img data-src="holder.js/180x180" alt="{{ photo.title }}" src="{{ photo.get_uri() }}" style="height: 180px; width: 180px%; display: block;">
                    </a>
                </div>
            {% if loop.index0 % 4 == 3 or loop.last %}
            </div>
            {% endif %}
            {% endfor %}
            <hr />

            <div class="btn-group">
                {% if album.people_id == g.user.id %}
                <a href="{{ url_for('photo.upload_photo', id=album.id) }}" class="btn btn-primary">上传照片</a>
                {% if album.title != '默认相册' %}
                <a href="{{ url_for('photo.modify_album', id=album.id) }}" class="btn btn-primary">修改属性</a>
                <a href="{{ url_for('photo.delete_album', id=album.id) }}" class="btn btn-primary">删除相册</a>
                {% endif %}
                {% endif %}
                <a href="{{ url_for('frontend.album', id=album.people_id) }}" class="btn btn-primary">返回</a>
            </div>

        </div>
    </div>
</div>
{% endblock %}

microblog/themes/newstyle/templates/photo/all-albums.html
{% extends theme('layout.html') %}
{% set active = 'album' %}
{% block title %}相册 | {{ title }}{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-3">
            {{ img_avatar(people) }}
            <h4 class="text-center">{{ people.nickname }}</h4>
            <hr />
        </div>
        <div class="col-lg-9">
            <h2>所有相册</h2>
            <hr />
            {% for album in people.albums %}
            {% if loop.index0 % 4 == 0 %}
            <div class="row">
            {% endif %}
                <div class="col-lg-3">
                    <a href="{{ url_for('photo.show_album', id=album.id) }}" class="thumbnail">
                        <img data-src="holder.js/180x180" alt="{{ album.title }}" src="{{ album.photos.first().get_uri() if album.photos.count() else theme_static('image/default-cover.png') }}" style="height: 180px; width: 180px%; display: block;">
                    </a>
                </div>
            {% if loop.index0 % 4 == 3 or loop.last %}
            </div>
            {% endif %}
            {% endfor %}
            {% if people.id == g.user.id %}
            <hr />
            <div class="btn-group">
                <a href="{{ url_for('photo.upload_photo') }}" class="btn btn-primary">上传照片</a>
                <a href="{{ url_for('photo.add_album') }}" class="btn btn-primary">新建相册</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

microblog/themes/newstyle/templates/photo/photo-info.html
{% extends theme('layout.html') %}
{% set active = 'album' %}
{% block title %}相册 | {{ title }}{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-3">
            {{ img_avatar(g.user) }}
            <hr />
        </div>
        <div class="col-lg-9">
            <form class="form-horizontal" role="form" action="" method="POST">
                <div class="form-group">
                    {{ form.description.label(class_='col-lg-2 control-label') }}
                    <div class="col-lg-6">
                        {{ form.description(class_='form-control', rows=6) }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-6">
                        {{ form.submit(class_='btn btn-primary') }}
                    </div>
                </div>
                {{ form.hidden_tag() }}

            </form>
        </div>
    </div>
</div>
{% endblock %}

microblog/themes/newstyle/templates/photo/photo.html
{% extends theme('layout.html') %}
{% set active = 'album' %}
{% block title %}相册 | {{ title }}{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-3">
            {{ img_avatar(photo.people) }}
            <h4 class="text-center">{{ photo.people.nickname }}</h4>
            <hr />
        </div>
        <div class="col-lg-9">
            <div class="text-center">
            <img src="{{ photo.get_uri() }}" alt="{{ photo.title }}" class="img-thumbnail">
            </div>
            {% if photo.description %}
            <hr />
            <p class="text-muted">{{ photo.description }}</p>
            {% endif %}
            <hr />
            <div class="btn-group">
                {% if photo.people_id == g.user.id %}
                <a href="{{ url_for('photo.modify_photo', id=photo.id) }}" class="btn btn-primary">修改属性</a>
                <a href="{{ url_for('photo.delete_photo', id=photo.id) }}" class="btn btn-primary">删除照片</a>
                {% endif %}
                {% if photo.album_id %}
                <a href="{{ url_for('photo.show_album', id=photo.album_id) }}" class="btn btn-primary">返回</a>
                {% endif %}
            </div>
            <div class="btn-group">
                {% if prev_id %}
                <a href="{{ url_for('photo.show_photo', pid=prev_id, aid=photo.album_id) }}" class="btn btn-primary">上一张</a>
                {% endif %}
                {% if next_id %}
                <a href="{{ url_for('photo.show_photo', pid=next_id, aid=photo.album_id) }}" class="btn btn-primary">下一张</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

microblog/themes/newstyle/templates/photo/upload.html
{% extends theme('layout.html') %}
{% set active = 'album' %}
{% block title %}相册 | {{ title }}{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-3">
            {{ img_avatar(g.user) }}
            <hr />
        </div>
        <div class="col-lg-9">
            <form class="form-horizontal" role="form" action="" method="POST" enctype="multipart/form-data">

                {% for field in form %}
                {% if 'album' in field.name %}
                <div class="form-group">
                    {{ field.label(class_='col-lg-2 control-label') }}
                    <div class="col-lg-6">
                        {{ field(class_='form-control') }}
                    </div>
                </div>
                {% elif 'photo' in field.name %}
                <div class="form-group">
                    {{ field.label(class_='col-lg-2 control-label') }}
                    <div class="col-lg-6">
                        {{ field(class_='form-control', accept='image/*') }}
                    </div>
                </div>
                {% elif 'submit' in field.name %}
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-6">
                        {{ field(class_='btn btn-primary') }}
                    </div>
                </div>
                {% endif %}
                {% endfor %}
                {{ form.hidden_tag() }}

            </form>
        </div>
    </div>
</div>
{% endblock %}