microblog/models/post.py
# -*- coding: utf-8 -*-
from microblog.database import db
import datetime
from microblog.models.accounts import People


class Microblog(db.Model):
    __tablename__ = 'microblog'

    id = db.Column(db.Integer, primary_key=True)
    people_id = db.Column(
        db.Integer,
        db.ForeignKey(People.id, ondelete='CASCADE'),
        nullable=False
    )
    content = db.Column(db.Text, nullable=False)
    post_time = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    def __init__(self, people_id, content):
        self.people_id = people_id
        self.content = content

microblog/forms/post.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(Form):
    content = TextAreaField(u'内容', validators=[DataRequired(message=u'请输入微博内容')])
    submit = SubmitField(u'发布')


microblog/views/account.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime

from flask import Blueprint, g, request, url_for, redirect, flash, current_app, session
from flask.ext.login import login_user, login_required, logout_user
from flask.ext.principal import identity_changed, Identity, AnonymousIdentity

from microblog.extensions import db
from microblog.forms.account import ModifyProfileDetailForm
from microblog.models import People, LoginLog
from microblog.forms import LoginForm, RegisterForm, ChangePasswordForm, ModifyProfileForm, AvatarForm
from microblog.helpers import get_client_ip, get_uploader, render_template
from microblog.models.account import PeopleInfo


account = Blueprint('account', __name__, url_prefix='/account')


# 用户注册
@account.route('/register/', methods=['GET', 'POST'])
def register():
    # 已登录用户则返回首页
    if g.user.is_authenticated:
        return redirect(url_for('frontend.index'))

    register_form = RegisterForm()
    if register_form.validate_on_submit():
        ip = get_client_ip()
        people = People(
            email=register_form.email.data,
            password=register_form.password.data,
            nickname=register_form.nickname.data,
            mobile=register_form.mobile.data,
            reg_time=datetime.datetime.utcnow(),
            reg_ip=ip,
        )
        # 将用户写入数据库
        db.session.add(people)
        db.session.commit()
        db.session.close()
        flash('注册成功', 'success')
        return redirect(url_for('frontend.index'))
    return render_template('register.html', register_form=register_form)


@account.route('/login/', methods=['GET', 'POST'])
def login():
    # 已登录用户则返回首页
    if g.user.is_authenticated:
        return redirect(url_for('frontend.index'))

    login_form = LoginForm()
    if login_form.validate_on_submit():
        people = People.query.authenticate(
            login_form.login.data,
            login_form.password.data,
        )

        if people:
            login_user(people, remember=login_form.remember.data)
            # Flask-Principal 发送信号
            identity_changed.send(current_app._get_current_object(), identity=Identity(people.id))
            print 'sent by login'
            ip = get_client_ip()
            login_log = LoginLog(people.id, ip)
            db.session.add(login_log)
            db.session.commit()

            flash('登录成功', 'success')
            return redirect(url_for('frontend.index'))
        else:
            flash('登录失败', 'warning')

    return render_template('login.html', form=login_form)


# 注销
@account.route('/logout/')
@login_required
def logout():
    logout_user()
    # Remove session keys set by Flask-Principal
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)
    # Tell Flask-Principal the user is anonymous
    identity_changed.send(current_app._get_current_object(), identity=AnonymousIdentity())
    print 'sent by logout'
    flash('已注销', 'success')
    return redirect(url_for('frontend.index'))


# 修改密码
@account.route('/password/', methods=['GET', 'POST'])
@login_required
def password():
    change_password_form = ChangePasswordForm()
    if change_password_form.validate_on_submit():
        people = People.query.authenticate(
            g.user.get_email(),
            change_password_form.password_old.data,
        )
        if people:
            people.change_password(change_password_form.password_new.data)
            db.session.add(people)
            db.session.commit()
            db.session.close()
            flash('密码修改成功', 'success')
            return redirect(url_for('account.password'))
        else:
            flash('原密码不正确', 'warning')
    return render_template('password.html', form=change_password_form, title='修改密码')


# 显示与修改个人资料
@account.route('/profile/', methods=['GET', 'POST'])
@login_required
def profile():
    people = g.user
    profile_form = ModifyProfileForm(obj=people)
    if profile_form.validate_on_submit():
        #new_password = profile_form.password.data
        new_nickname = profile_form.nickname.data
        new_mobile = profile_form.mobile.data
        #if new_password:
        #    people.change_password(new_password)
        if new_nickname:
            people.change_nickname(new_nickname)
        if new_mobile:
            people.change_mobile(new_mobile)
        db.session.add(people)
        db.session.commit()
        db.session.close()
        flash('个人资料修改成功', 'success')
        return redirect(url_for('account.profile'))
    return render_template('profile.html', form=profile_form, title='修改资料')


# 显示与修改详细资料
@account.route('/profile/detail/', methods=['GET', 'POST'])
@login_required
def profile_detail():
    people_info = PeopleInfo.query.get(g.user.id)
    profile_detail_form = ModifyProfileDetailForm(obj=people_info)
    if profile_detail_form.validate_on_submit():
        if people_info:
            people_info.change_info(
                fullname=profile_detail_form.fullname.data,
                gender=profile_detail_form.gender.data,
                sexual_orientation=profile_detail_form.sexual_orientation.data,
                birthday=profile_detail_form.birthday.data,
                blood_type=profile_detail_form.blood_type.data,
                profession=profile_detail_form.profession.data,
                education=profile_detail_form.education.data,
                school=profile_detail_form.school.data,
                homepage=profile_detail_form.homepage.data,
                hometown=profile_detail_form.hometown.data,
                location=profile_detail_form.location.data,
                address=profile_detail_form.address.data,
                zip_code=profile_detail_form.zip_code.data,
                qq=profile_detail_form.qq.data,
                introduction=profile_detail_form.introduction.data
            )
        else:
            people_info = PeopleInfo(
                id=g.user.id,
                fullname=profile_detail_form.fullname.data,
                gender=profile_detail_form.gender.data,
                sexual_orientation=profile_detail_form.sexual_orientation.data,
                birthday=profile_detail_form.birthday.data,
                blood_type=profile_detail_form.blood_type.data,
                profession=profile_detail_form.profession.data,
                education=profile_detail_form.education.data,
                school=profile_detail_form.school.data,
                homepage=profile_detail_form.homepage.data,
                hometown=profile_detail_form.hometown.data,
                location=profile_detail_form.location.data,
                address=profile_detail_form.address.data,
                zip_code=profile_detail_form.zip_code.data,
                qq=profile_detail_form.qq.data,
                introduction=profile_detail_form.introduction.data
            )
        db.session.add(people_info)
        db.session.commit()
        flash('详细资料修改成功', 'success')
        return redirect(url_for('account.profile_detail'))
    return render_template('profile-detail.html', form=profile_detail_form, title='详细资料')


@account.route('/avatar/', methods=['GET', 'POST'])
@login_required
def avatar():
    avatar_form = AvatarForm()
    if avatar_form.validate_on_submit():
        if avatar_form.avatar.data:
            # 上传头像
            avatar_filename = g.user.get_avatar_uri()
            avatar_data = request.files[avatar_form.avatar.name]
            uploader = get_uploader()
            avatar_filename = uploader.save(avatar_data)
            if not avatar_filename:
                flash('上传失败', 'danger')
                return redirect(url_for('account.avatar'))
            # url = photos.url(avatar_filename)
            # print url
            # old_avatar = photos.url(people.avatar)
            # os.remove(old_avatar)   # 删除旧头像
            print avatar_filename
            g.user.change_avatar(avatar_filename)
            db.session.add(g.user)
            db.session.commit()
            flash('上传成功', 'success')
            return redirect(url_for('account.avatar'))

    return render_template('avatar.html', avatar_form=avatar_form, title='修改头像')

microblog/views/frontend.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os
import StringIO

from flask import Blueprint, g, url_for, redirect, send_from_directory, \
    current_app, abort, request, session

from microblog.models import People, Microblog
from microblog.forms import PostForm
from microblog.captcha import create_captcha
from microblog.helpers import render_template

frontend = Blueprint('frontend', __name__)


@frontend.route('/favicon.ico')
def favicon():
    return send_from_directory(
        'static',
        'favicon.ico',
        mimetype='image/vnd.microsoft.icon'
    )


@frontend.route('/')
def index():
    if g.user.is_authenticated:
        # 只显示关注的人
        microblogs = Microblog.query.\
            filter(Microblog.people_id.in_([p.id for p in g.user.following]+[g.user.id])).\
            order_by(Microblog.post_time.desc()).all()
    else:
        microblogs = Microblog.query.order_by(Microblog.post_time.desc()).limit(10).all()
    # print microblogs
    return render_template('index.html', microblogs=microblogs, post_form=PostForm())


@frontend.route('/square/')
def square():
    microblogs = Microblog.query.order_by(Microblog.post_time.desc()).all()
    # print microblogs
    return render_template('square.html', microblogs=microblogs, post_form=PostForm())


@frontend.route('/people/<int:id>/')
def people(id):
    people = People.query.get_or_404(id)
    return render_template('people.html', people=people)


@frontend.route('/people/<int:id>/album/')
def album(id):
    people = People.query.get_or_404(id)
    # albums = PhotoAlbum.query.filter_by(people_id=id).all()
    # default_album_photos = Photo.query.filter_by(people_id=id).all()
    return render_template('photo/all-albums.html', people=people, title='所有相册')


@frontend.route('/uploads/photos/<filename>')
def uploads(filename):
    if not current_app.config['USE_BCS_BUCKET']:
        return send_from_directory(
            os.path.abspath(current_app.config['UPLOADS_DIR']),
            filename
        )
    else:
        return redirect(
            'http://bcs.duapp.com/' +
            current_app.config['BCS_BUCKET_NAME'] +
            '/' + filename
        )


@frontend.route('/remote/photo/')
def remote_photo():
    uri = request.args.get('uri', None)
    return redirect(uri)


@frontend.route('/captcha/')
def get_captcha():
    #把 strs 发给前端,或者在后台使用session保存
    img, strs = create_captcha(
        size=(90, 43), img_type="PNG", 
        font_type="microblog/static/fonts/ALGER.TTF",
    )
    buf = StringIO.StringIO()
    img.save(buf, 'PNG')
    session['captcha'] = strs
    response = current_app.make_response(buf.getvalue())
    response.headers['Content-Type'] = 'image/png'
    return response


@frontend.route('/about/')
def show_about():
    return render_template('about.html')
    
    
@frontend.route('/test/<int:error>/')
def test(error):
    """HTTP 错误测试"""
    if error in (404, 500):
        abort(error)
    else:
        return redirect(url_for('frontend.index'))

microblog/views/mblog.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from flask import Blueprint, g, url_for, redirect, flash, abort, request
from flask.ext.login import login_required

from microblog.extensions import db
from microblog.models import Microblog, Comment
from microblog.forms import PostForm, CommentForm, RepostForm
from microblog.models.notification import Notification
from microblog.helpers import render_template


mblog = Blueprint('mblog', __name__, url_prefix='/microblog')


# 发布微博
@mblog.route('/post/', methods=['GET', 'POST'])
@login_required
def post():
    post_form = PostForm()
    if post_form.validate_on_submit():
        microblog = Microblog(g.user.id, post_form.content.data)
        db.session.add(microblog)
        db.session.commit()
        flash('发布成功', 'success')
        return redirect(url_for('frontend.index'))
    return render_template('post.html', form=post_form)


@mblog.route('/<int:id>/delete/')
@login_required
def delete(id):
    microblog = Microblog.query.get_or_404(id)
    if microblog.people_id == g.user.id:
        db.session.delete(microblog)
        db.session.commit()
        flash('删除成功', 'success')
        # print '删除成功'
    else:
        flash('删除失败', 'warning')
        # print '删除失败'
    return redirect(url_for('frontend.index'))


@mblog.route('/<int:mid>/comment/', methods=['GET', 'POST'])
@mblog.route('/<int:mid>/comment/<int:cid>/', methods=['GET', 'POST'])
@login_required
def comment(mid, cid=None):
    microblog = Microblog.query.get_or_404(mid)

    # 如果是对评论的评论，则在表单中显示回复的目标（字符串）
    # 并在提交时使用切片运算忽略该字符串
    if cid:
        parent_comment = Comment.query.get_or_404(cid)
        # 不能回复自己
        if g.user.id == parent_comment.people.id:
            flash('不能回复自己', 'warning')
            return redirect(url_for('mblog.comment', mid=mid))
        content = '回复 ' + parent_comment.people.nickname + ': '
    else:
        parent_comment = None
        content = ''
    comment_form = CommentForm(content=content)
    if comment_form.validate_on_submit():
        comment = Comment(
            g.user.id,
            comment_form.content.data[len(content):],
            mid,
            cid
        )
        db.session.add(comment)
        db.session.commit()
        if cid and g.user.id != parent_comment.people_id:
            notification = Notification(
                from_id=g.user.id, to_id=parent_comment.people_id,
                object_table='comment', object_id=comment.id
            )
            db.session.add(notification)
            db.session.commit()
        elif g.user.id != microblog.people_id:
            notification = Notification(
                from_id=g.user.id, to_id=microblog.people_id,
                object_table='microblog', object_id=mid
            )
            db.session.add(notification)
            db.session.commit()
        flash('评论成功', 'success')
        return redirect(url_for('mblog.comment', mid=mid))
    return render_template(
        'comment.html',
        form=comment_form,
        microblog=microblog,
        parent_comment=parent_comment
    )


@mblog.route('/comment/<int:id>/delete/')
@login_required
def delete_comment(id):
    comment = Comment.query.get_or_404(id)
    mid = comment.microblog_id
    if comment.people_id == g.user.id:
        db.session.delete(comment)
        db.session.commit()
        flash('删除成功', 'success')
        # print '删除成功'
    else:
        flash('删除失败', 'warning')
        # print '删除失败'
    return redirect(url_for('mblog.comment', mid=mid))


@mblog.route('/<int:id>/repost/', methods=['GET', 'POST'])
@login_required
def repost(id):
    microblog = Microblog.query.get_or_404(id)
    repost_form = RepostForm()
    if repost_form.validate_on_submit():
        rp_microblog = Microblog(g.user.id, repost_form.content.data, parent_microblog_id=id)
        db.session.add(rp_microblog)
        if g.user.id != microblog.people_id:
            notification = Notification(
                from_id=g.user.id, to_id=microblog.people_id,
                object_table='microblog', object_id=id
            )
            db.session.add(notification)
        db.session.commit()
        flash('转发成功', 'success')
        return redirect(url_for('frontend.index'))
    return render_template('repost.html', form=repost_form, microblog=microblog)

microblog/themes/default/templates/avatar.html
<form method="POST" action="" enctype="multipart/form-data">
    <table>
        <tr>
            <th></th>
            <td>
                <a href="{{ url_for('frontend.uploads', filename=avatar) }}">
                    <img src="{{ url_for('frontend.uploads', filename=avatar) }}" style="width: 200px; height: 200px;" />
                </a>
            </td>
            <td></td>
        </tr>
        <tr>
            <th></th>
            <td>{{ avatar_form.avatar }}</td>
            <td>{{ ', '.join(avatar_form.avatar.errors) }}</td>
        </tr>
        <tr>
            <th></th>
            <td>{{ avatar_form.submit }}</td>
            <td></td>
        </tr>
    </table>
    {{ avatar_form.hidden_tag() }}
</form>

microblog/themes/default/templates/comment.html
<p>{{ microblog.content }} <a href="{{ url_for('frontend.people', id=microblog.people.id) }}">{{ microblog.people.nickname }}</a> {{ microblog.post_time }}</p>
{% if parent_comment %}
<p>回复： {{ parent_comment.content }} <a href="{{ url_for('frontend.people', id=parent_comment.people.id) }}">{{ parent_comment.people.nickname }}</a> {{ parent_comment.comment_time }}</p>
{% endif %}
<form method="POST" action="">
    <table>
        <tr>
            <th>{{ form.content.label }}</th>
            <td>{{ form.content }}</td>
            <td>{{ ', '.join(form.content.errors) }}</td>
        </tr>
        <tr>
            <th></th>
            <td>{{ form.submit }}</td>
            <td></td>
        </tr>
    </table>
    {{ form.hidden_tag() }}
</form>

microblog/themes/default/templates/index.html
<!doctype html>
<html>
<body>
    <p>欢迎，{{ g.user.get_nickname() if g.user.is_authenticated() else '游客' }}</p>
    <ul>
        {%- if not g.user.is_authenticated() %}
        <li><a href="{{ url_for('account.register') }}">注册</a></li>
        <li><a href="{{ url_for('account.login') }}">登录</a></li>
        {%- else %}
        <li><a href="{{ url_for('mblog.post') }}">发布微博</a></li>
        <li><a href="{{ url_for('account.profile') }}">个人资料</a></li>
        <li><a href="{{ url_for('account.password') }}">修改密码</a></li>
        <li><a href="{{ url_for('account.logout') }}">注销</a></li>
        {%- endif %}
    </ul>
    <ul>
    {% for microblog in microblogs %}
        <li><p>{{ microblog.content }}</p>
            <p><a href="{{ url_for('frontend.people', id=microblog.people.id) }}">{{ microblog.people.nickname }}</a> {{ microblog.post_time }}</p>
            <ul>
                {% for comment in microblog.comments %}
                <li>{{ comment.content }} <a href="{{ url_for('mblog.comment', mid=microblog.id, cid=comment.id) }}">回复</a></li>
                {% endfor %}
            </ul>
            {% if microblog.people_id==g.user.id %}
            <p>
                <a href="{{ url_for('mblog.delete', id=microblog.id) }}">删除</a>
                <a href="{{ url_for('mblog.comment', mid=microblog.id) }}">评论</a>
            </p>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
</body>
</html>

microblog/themes/default/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>{% blcok title %}{% endblock %}</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

microblog/themes/default/templates/login.html
<form method="POST" action="">
    <table>
        <tr>
            <th>{{ form.login.label }}</th>
            <td>{{ form.login }}</td>
            <td>{{ ', '.join(form.login.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.password.label }}</th>
            <td>{{ form.password }}</td>
            <td>{{ ', '.join(form.password.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.remember.label }}</th>
            <td>{{ form.remember }}</td>
            <td></td>
        </tr>
        <tr>
            <th></th>
            <td>{{ form.submit }}</td>
            <td></td>
        </tr>
    </table>
    {{ form.hidden_tag() }}
</form>

microblog/themes/default/templates/password.html
<form method="POST" action="">
    <table>
        <tr>
            <th>{{ form.password_old.label }}</th>
            <td>{{ form.password_old }}</td>
            <td>{{ ', '.join(form.password_old.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.password_new.label }}</th>
            <td>{{ form.password_new }}</td>
            <td>{{ ', '.join(form.password_new.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.password_confirm.label }}</th>
            <td>{{ form.password_confirm }}</td>
            <td>{{ ', '.join(form.password_confirm.errors) }}</td>
        </tr>
        <tr>
            <th></th>
            <td>{{ form.submit }}</td>
            <td></td>
        </tr>
    </table>
    {{ form.hidden_tag() }}
</form>

microblog/themes/default/templates/people.html
<table>
    <tr>
        <th>邮箱</th>
        <td>{{ people.email }}</td>
    </tr>
    <tr>
        <th>昵称</th>
        <td>{{ people.nickname }}</td>
    </tr>
    <tr>
        <th>手机</th>
        <td>{{ people.mobile }}</td>
    </tr>
</table>

microblog/themes/default/templates/post.html
<form method="POST" action="">
    <table>
        <tr>
            <th>{{ form.content.label }}</th>
            <td>{{ form.content }}</td>
            <td>{{ ', '.join(form.content.errors) }}</td>
        </tr>
        <tr>
            <th></th>
            <td>{{ form.submit }}</td>
            <td></td>
        </tr>
    </table>
    {{ form.hidden_tag() }}
</form>

microblog/themes/default/templates/profile.html
<form method="POST" action="">
    <table>
        <tr>
            <th></th>
            <td>
                <a href="{{ url_for('frontend.uploads', filename=avatar) }}">
                    <img src="{{ url_for('frontend.uploads', filename=avatar) }}" style="width: 200px; height: 200px;" />
                </a>
            </td>
            <td></td>
        </tr>
        <tr>
            <th>{{ form.email.label }}</th>
            <td>{{ form.email(readonly=True) }}</td>
            <td>{{ ', '.join(form.email.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.password.label }}</th>
            <td>{{ form.password }}</td>
            <td>{{ ', '.join(form.password.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.nickname.label }}</th>
            <td>{{ form.nickname }}</td>
            <td>{{ ', '.join(form.nickname.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.mobile.label }}</th>
            <td>{{ form.mobile }}</td>
            <td>{{ ', '.join(form.mobile.errors) }}</td>
        </tr>
        <tr>
            <th></th>
            <td>{{ form.submit }}</td>
            <td></td>
        </tr>
    </table>
    {{ form.hidden_tag() }}
</form>

microblog/themes/default/templates/register.html
<form method="POST" action="">
    <table>
        <tr>
            <th>{{ form.email.label }}</th>
            <td>{{ form.email }}</td>
            <td>{{ ', '.join(form.email.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.password.label }}</th>
            <td>{{ form.password }}</td>
            <td>{{ ', '.join(form.password.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.password_confirm.label }}</th>
            <td>{{ form.password_confirm }}</td>
            <td>{{ ', '.join(form.password_confirm.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.nickname.label }}</th>
            <td>{{ form.nickname }}</td>
            <td>{{ ', '.join(form.nickname.errors) }}</td>
        </tr>
        <tr>
            <th>{{ form.mobile.label }}</th>
            <td>{{ form.mobile }}</td>
            <td>{{ ', '.join(form.mobile.errors) }}</td>
        </tr>
        <tr>
            <th></th>
            <td>{{ form.submit }}</td>
            <td></td>
        </tr>
    </table>
    {{ form.hidden_tag() }}
</form>