microblog/models/post.py
# -*- coding: utf-8 -*-
from microblog.database import db
import datetime
from microblog.models.accounts import People


class Microblog(db.Model):
    __tablename__ = 'microblog'

    id = db.Column(db.Integer, primary_key=True)
    people_id = db.Column(
        db.Integer,
        db.ForeignKey(People.id, ondelete='CASCADE'),
        nullable=False
    )
    content = db.Column(db.Text, nullable=False)
    post_time = db.Column(db.DateTime, default=datetime.datetime.utcnow)

    def __init__(self, people_id, content):
        self.people_id = people_id
        self.content = content

microblog/forms/friendship.py
# -*- coding: utf-8 -*-
from flask.ext.wtf import Form
from wtforms import TextAreaField, SubmitField, TextField
from wtforms.validators import DataRequired


class ChatForm(Form):
    content = TextAreaField(u'内容', validators=[DataRequired(message=u'请输入聊天内容')])
    submit = SubmitField(u'发送')


class AddGroupForm(Form):
    name = TextField(
        u'名称',
        validators=[DataRequired(message=u'请输入分组名称')],
    )
    submit = SubmitField(u'新建')


class RenameGroupForm(AddGroupForm):
    submit = SubmitField(u'修改')

microblog/forms/post.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(Form):
    content = TextAreaField(u'内容', validators=[DataRequired(message=u'请输入微博内容')])
    submit = SubmitField(u'发布')


microblog/views/admin.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from flask import Blueprint, redirect, url_for, flash
from flask.ext.login import login_required

from microblog.extensions import db
from microblog.models import People, Microblog, LoginLog, VisitLog
from microblog.permission import admin as admin_permission
from microblog.helpers import render_template


admin = Blueprint('admin', __name__, url_prefix='/admin')


@admin.route('/')
@login_required
@admin_permission.require(401)
def index():
    return render_template('admin/index.html')


@admin.route('/people/', defaults={'page': 1})
@admin.route('/people/page/<int:page>/')
@login_required
@admin_permission.require(401)
def show_people(page):
    pagination = People.query.paginate(page, per_page=50)
    people = pagination.items
    return render_template(
        'admin/people.html',
        people=people,
        pagination=pagination
    )


@admin.route('/people/block/<int:id>/')
@login_required
@admin_permission.require(401)
def block_people(id):
    people = People.query.get_or_404(id)
    if people.status != 'blocked':
        people.status = 'blocked'
        db.session.add(people)
        db.session.commit()
        flash('禁言成功', 'success')
    return redirect(url_for('show_people'))


@admin.route('/people/unblock/<int:id>/')
@login_required
@admin_permission.require(401)
def unblock_people(id):
    people = People.query.get_or_404(id)
    if people.status != 'active':
        people.status = 'active'
        db.session.add(people)
        db.session.commit()
        flash('取消禁言成功', 'success')
    return redirect(url_for('show_people'))


@admin.route('/people/delete/<int:id>/')
@login_required
@admin_permission.require(401)
def delete_people(id):
    people = People.query.get_or_404(id)
    people.status = 'deleted'
    db.session.add(people)
    db.session.commit()
    flash('用户已删除', 'success')
    return redirect(url_for('show_people'))


@admin.route('/microblog/', defaults={'page': 1})
@admin.route('/microblog/page/<int:page>/')
@login_required
@admin_permission.require(401)
def show_microblog(page):
    pagination = Microblog.query.order_by(Microblog.post_time.desc()).\
        paginate(page, per_page=50)
    microblogs = pagination.items
    return render_template(
        'admin/microblog.html',
        microblogs=microblogs,
        pagination=pagination
    )


@admin.route('/microblog/delete/<int:id>/')
@login_required
@admin_permission.require(401)
def delete_microblog(id):
    microblog = Microblog.query.get_or_404(id)
    db.session.delete(microblog)
    db.session.commit()
    flash('微博已删除', 'success')
    return redirect(url_for('show_microblog'))


@admin.route('/login-log/', defaults={'page': 1})
@admin.route('/login-log/page/<int:page>/')
@login_required
@admin_permission.require(401)
def show_login_log(page):
    pagination = LoginLog.query.order_by(LoginLog.login_time.desc()).\
        paginate(page, per_page=50)
    login_logs = pagination.items
    return render_template(
        'admin/login-log.html',
        login_logs=login_logs,
        pagination=pagination
    )


@admin.route('/visit-log/', defaults={'page': 1})
@admin.route('/visit-log/page/<int:page>/')
@login_required
@admin_permission.require(401)
def show_visit_log(page):
    pagination = VisitLog.query.order_by(VisitLog.visit_time.desc()).\
        paginate(page, per_page=50)
    # For BAE fucking MySQL
    # pagination = VisitLog.query.paginate(page, per_page=50)
    visit_logs = pagination.items
    return render_template(
        'admin/visit-log.html',
        visit_logs=visit_logs,
        pagination=pagination
    )


@admin.route('/visit-log/<int:id>/delete/')
@login_required
@admin_permission.require(401)
def delete_visit_log(id):
    visit_log = VisitLog.query.get(id)
    db.session.delete(visit_log)
    db.session.commit()
    return redirect(url_for('show_visit_log'))


@admin.route('/install/')
def install():
    db.create_all()
    flash('数据库初始化成功', 'success')
    return redirect(url_for('frontend.index'))

microblog/views/friendship.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from flask import Blueprint, g, redirect, url_for, flash, abort, current_app, render_template
from flask.ext.login import login_required
from sqlalchemy import and_
from microblog.forms import ChatForm, AddGroupForm, RenameGroupForm
from microblog.models import People, Friendship, Chatting, Group, Blackship, Notification
from microblog.extensions import db


friendship = Blueprint('friendship', __name__, url_prefix='/friendship')


@friendship.route('/follow/<int:id>/')
@login_required
def follow(id):
    """关注"""
    if g.user.id == id:
        flash('不能关注自己', 'warning')
    else:
        people = People.query.get_or_404(id)
        if g.user.is_following(id):
            flash('不能重复关注', 'warning')
        elif g.user.is_blocking(id):
            flash('不能关注黑名单中的人，请先移出黑名单', 'warning')
        elif people.is_blocking(g.user.id):
            flash('对方拒绝了您的关注请求', 'warning')
        else:
            g.user.following.append(people)
            db.session.add(g.user)
            notification = Notification(from_id=g.user.id, to_id=id, object_table='friendship')
            db.session.add(notification)
            db.session.commit()
            flash('关注成功', 'success')
    return redirect(url_for('frontend.index'))


@friendship.route('/unfollow/<int:id>/')
@login_required
def unfollow(id):
    """取消关注"""
    people = People.query.get_or_404(id)
    if g.user.is_following(id):
        g.user.following.remove(people)
        db.session.add(g.user)
        db.session.commit()
        flash('取消成功', 'success')
    return redirect(url_for('frontend.index'))


@friendship.route('/following/', defaults={'page': 1})
@friendship.route('/following/page/<int:page>/')
@friendship.route('/following/group/<int:gid>/', defaults={'page': 1})
@friendship.route('/following/group/<int:gid>/page/<int:page>/')
@login_required
def show_following(page, gid=None):
    """查看我关注的人"""
    if not gid:
        pagination = g.user.following.order_by(Friendship.c.follow_time).paginate(page, per_page=current_app.config['PER_PAGE'])
        following = pagination.items
        rename_group_form = None
    else:
        pagination = g.user.following.filter(Friendship.c.group_id==gid).order_by(Friendship.c.follow_time).paginate(page, per_page=current_app.config['PER_PAGE'])
        following = pagination.items
        group = Group.query.get_or_404(gid)
        rename_group_form = RenameGroupForm(obj=group)

    add_group_form = AddGroupForm()
    return render_template('friendship.html',
                           people=following,
                           pagination=pagination,
                           active_page='show_following',
                           active_gid=gid,
                           add_group_form=add_group_form,
                           rename_group_form=rename_group_form,
                           title='我关注的')


@friendship.route('/followed/', defaults={'page': 1})
@friendship.route('/followed/page/<int:page>/')
@login_required
def show_followed(page):
    """查看关注我的人"""
    pagination = g.user.followed.order_by(Friendship.c.follow_time).paginate(page, per_page=current_app.config['PER_PAGE'])
    followed = pagination.items
    return render_template('friendship.html',
                           people=followed,
                           pagination=pagination,
                           active_page='show_followed',
                           title='关注我的')


@friendship.route('/mutual/', defaults={'page': 1})
@friendship.route('/mutual/page/<int:page>/')
@login_required
def show_mutual(page):
    """查看互相关注的人"""
    pagination = g.user.get_mutual().order_by(Friendship.c.follow_time).paginate(page, per_page=current_app.config['PER_PAGE'])
    # pagination = g.user.followed.filter(Friendship.c.to_id==g.user.id).\
    #     order_by(Friendship.c.follow_time).paginate(page, per_page=10)
    mutual = pagination.items
    return render_template('friendship.html',
                           people=mutual,
                           pagination=pagination,
                           active_page='show_mutual',
                           title='互相关注')


@friendship.route('/block/<int:id>/')
@login_required
def block(id):
    if g.user.id == id:
        flash('不能将自己加入黑名单', 'warning')
    else:
        people = People.query.get_or_404(id)
        if g.user.is_blocking(id):
            flash('不能重复加入黑名单', 'warning')
        else:
            g.user.blocking.append(people)
            # 取消关注
            if g.user.is_following(id):
                g.user.following.remove(people)
            if people.is_following(g.user.id):
                g.user.followed.remove(people)
            db.session.add(g.user)
            db.session.commit()
            flash('加入黑名单成功', 'success')
    return redirect(url_for('frontend.index'))


@friendship.route('/unblock/<int:id>/')
@login_required
def unblock(id):
    people = People.query.get_or_404(id)
    if g.user.is_blocking(id):
        g.user.blocking.remove(people)
        db.session.add(g.user)
        db.session.commit()
        flash('取消黑名单成功', 'success')
    return redirect(url_for('frontend.index'))


@friendship.route('/blocking/', defaults={'page': 1})
@friendship.route('/blocking/page/<int:page>/')
@login_required
def show_blocking(page):
    """查看黑名单"""
    pagination = g.user.blocking.order_by(Blackship.c.block_time.desc()).paginate(page, per_page=current_app.config['PER_PAGE'])
    blocking = pagination.items
    return render_template('friendship.html',
                           people=blocking,
                           pagination=pagination,
                           active_page='show_blocking',
                           title='黑名单')


@friendship.route('/chat/<int:id>/', methods=['GET', 'POST'])
@login_required
def send_chatting(id):
    if g.user.id == id:
        flash('不能给自己发送私信', 'warning')
        return redirect(url_for('frontend.index'))
    chat_form = ChatForm()
    from_people = g.user
    to_people = People.query.get_or_404(id)

    if chat_form.validate_on_submit():
        chatting = Chatting(from_people.id, to_people.id, content=chat_form.content.data)
        db.session.add(chatting)
        db.session.commit()
        notification = Notification(from_id=g.user.id, to_id=id, object_table='chatting', object_id=chatting.id)
        db.session.add(notification)
        db.session.commit()
        flash('发送成功', 'success')
        return redirect(url_for('frontend.index'))

    return render_template(
        'chatting-new.html',
        chat_form=chat_form,
        from_people=from_people,
        to_people=to_people
    )


@friendship.route('/chat/inbox/', defaults={'page': 1})
@friendship.route('/chat/inbox/page/<int:page>/')
@friendship.route('/chat/inbox/<flag>/', defaults={'page': 1})
@friendship.route('/chat/inbox/<flag>/page/<int:page>/')
@login_required
def show_inbox(page, flag=None):
    if flag in ('hasread', 'unread'):
        has_read = False if flag == 'unread' else True
        pagination = Chatting.query.filter_by(to_id=g.user.id, has_read=has_read).order_by(Chatting.chat_time.desc()).paginate(page, per_page=current_app.config['PER_PAGE'])
    elif not flag:
        pagination = Chatting.query.filter_by(to_id=g.user.id).order_by(Chatting.chat_time.desc()).paginate(page, per_page=current_app.config['PER_PAGE'])
    else:
        abort(404)
    chattings = pagination.items

    return render_template('chatting-box.html',
                           box='inbox',
                           flag=flag,
                           chattings=chattings,
                           pagination=pagination)


@friendship.route('/chat/detail/<box>/<int:id>/')
@login_required
def show_chatting_detail(box, id):
    if box not in ('inbox', 'outbox'):
        abort(404)
    chatting = Chatting.query.get_or_404(id)
    if box == 'inbox' and chatting.to_id == g.user.id:
        chatting.has_read = True
        db.session.add(chatting)
        db.session.commit()
        # 标记为已读
    return render_template('chatting-detail.html', chatting=chatting)


@friendship.route('/chat/outbox/', defaults={'page': 1})
@friendship.route('/chat/outbox/page/<int:page>/')
@login_required
def show_outbox(page):
    pagination = Chatting.query.filter_by(from_id=g.user.id).order_by(Chatting.chat_time.desc()).paginate(page, per_page=current_app.config['PER_PAGE'])
    chattings = pagination.items
    return render_template('chatting-box.html',
                           box='outbox',
                           chattings=chattings,
                           pagination=pagination)


@friendship.route('/following/group/add/', methods=['GET', 'POST'])
@login_required
def add_group():
    group_form = AddGroupForm()
    if group_form.validate_on_submit():
        group = Group(name=group_form.name.data, people_id=g.user.id)
        db.session.add(group)
        db.session.commit()
        flash('新建成功', 'success')
        return redirect(url_for('friendship.show_following'))
    return render_template('group.html', form=group_form)


@friendship.route('/following/group/delete/<int:id>/')
@login_required
def delete_group(id):
    group = Group.query.get_or_404(id)
    if group in g.user.groups:
        db.session.delete(group)
        db.session.commit()
        flash('删除成功', 'success')
    return redirect(url_for('friendship.show_following'))


@friendship.route('/following/group/rename/<int:id>/', methods=['GET', 'POST'])
@login_required
def rename_group(id):
    group = Group.query.get_or_404(id)
    group_form = RenameGroupForm()
    if group.people_id == g.user.id:
        if group_form.validate_on_submit():
            group.name = group_form.name.data
            db.session.add(group)
            db.session.commit()
            flash('重命名成功', 'success')
            return redirect(url_for('friendship.show_following', gid=id))
    else:
        flash('权限不足', 'warning')
    return render_template('group.html', form=group_form)

microblog/views/notification.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from flask import Blueprint, g, flash, redirect, url_for
from flask.ext.login import login_required

from microblog.extensions import db
from microblog.models import Notification
from microblog.helpers import render_template


notification = Blueprint('notification', __name__, url_prefix='/notification')


@notification.route('/')
@login_required
def show_notification():
    notifications = Notification.query.filter_by(to_id=g.user.id).order_by(Notification.create_time.desc()).all()
    return render_template('notification.html', notifications=notifications)


@notification.route('/<int:id>/set-read/')
@login_required
def set_read(id):
    """标记为已读"""
    noti = Notification.query.get_or_404(id)
    if noti.to_id != g.user.id:
        flash('权限不足', 'warning')
        return redirect(url_for('notification.show_notification'))
    if not noti.has_read:
        noti.has_read = True
        db.session.add(noti)
        db.session.commit()
    return redirect(url_for('notification.show_notification'))


@notification.route('/<int:id>/set-unread/')
@login_required
def set_unread(id):
    """标记为已读"""
    noti = Notification.query.get_or_404(id)
    if noti.to_id != g.user.id:
        flash('权限不足', 'warning')
        return redirect(url_for('notification.show_notification'))
    if noti.has_read:
        noti.has_read = False
        db.session.add(noti)
        db.session.commit()
    return redirect(url_for('notification.show_notification'))


@notification.route('/<int:id>/delete/')
@login_required
def delete_notification(id):
    noti = Notification.query.get_or_404(id)
    if noti.to_id != g.user.id:
        flash('权限不足', 'warning')
        return redirect(url_for('notification.show_notification'))
    db.session.delete(noti)
    db.session.commit()
    flash('删除成功', 'success')
    return redirect(url_for('notification.show_notification'))

microblog/themes/newstyle/templates/about.html
{% extends theme('layout.html') %}
{% set active = 'about' %}
{% block title %}关于{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h4>孵化历程</h4>
            <ul>
                <li><a href="http://whypro.duapp.com" target="_blank">鳗鱼の工作室</a></li>
                <li><a href="http://vieboo.duapp.com" target="_blank">Vieboo</a></li>
            </ul>
            <h4>核心技术</h4>
            <ul>
                <li><a href="http://www.python.org/" target="_blank">Python</a></li>
                <li><a href="http://www.sqlalchemy.org/" target="_blank">SQLAlchemy</a></li>
                <li><a href="http://www.mongodb.org/" target="_blank">MongoDB</a></li>
                <li><a href="http://getbootstrap.com/" target="_blank">Bootstrap</a></li>
                <li><a href="http://www.github.com/">Git</a></li>
                <li><a href="http://sphinx-doc.org/">Sphinx</a></li>
            </ul>
            <p>
                诚邀<strong>产品设计师</strong>，<strong>前端工程师</strong>，<strong>技术翻译</strong>，<strong>Python Geek</strong>，合力打团！
            </p>
            <p>
                欢迎邮件骚扰：whypro#live.cn
            </p>
            <p>2014-01, By WHYPRO</p>
        </div>
    </div>
</div>
{% endblock %}

microblog/themes/newstyle/templates/avatar.html
{% extends theme('layout.html') %}
{% set active = 'profile' %}
{% block title %}个人资料 | {{ title }}{% endblock %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-lg-3">
            {{ img_avatar(g.user) }}
            <hr />
            <div class="divider"></div>
            <ul class="nav nav-pills nav-stacked">
                <li><a href="{{ url_for('account.profile') }}">基本资料</a></li>
                <li><a href="{{ url_for('account.profile_detail') }}">详细资料</a></li>
                <li><a href="{{ url_for('account.password') }}">修改密码</a></li>
                <li class="active"><a href="{{ url_for('account.avatar') }}">修改头像</a></li>
            </ul>
        </div>
        <div class="col-lg-9">

            <form class="form-horizontal" role="form" action="" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    {{ avatar_form.avatar.label(class_="col-lg-2 control-label") }}
                    <div class="col-lg-6">
                        <div class="input-group">
                            {{ avatar_form.avatar(class_="form-control", accept="image/*") }}
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-6">
                        {{ avatar_form.submit(class_="btn btn-primary") }}
                    </div>
                </div>
                {{ avatar_form.hidden_tag() }}

            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
$(document).ready(function(){
  $("#avatar_uri").focusin(function(){
    $("#avatar-type-1").attr("checked",true);
  });
  $("#avatar").focusin(function(){
    $("#avatar-type-0").attr("checked",true);
  });
});
</script>
{% endblock %}

microblog/themes/newstyle/templates/chatting-new.html
{% extends theme('layout.html') %}
{% set active = 'chatting' %}
{% block title %}私信 | 写私信{% endblock %}
{% block content %}
<div class="container">
    <div class="row">  
        <div class="col-lg-3">
            <div class="input-group">
                <input type="text" class="form-control" />
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">搜索</button>
                </span>
            </div>
            <hr />
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a>写私信</a></li>
                <li><a href="{{ url_for('friendship.show_inbox') }}"><span class="badge pull-right">{{ g.user.received_chattings.count() }}</span>收件箱</a></li>
                <li><a href="{{ url_for('friendship.show_outbox') }}"><span class="badge pull-right">{{ g.user.sent_chattings.count() }}</span>发件箱</a></li>
            </ul>
        </div>
        <div class="col-lg-9">
            <form class="form-horizontal" role="form" action="" method="POST">
                <div class="form-group">
                    <label for="people" class="col-lg-2 control-label">收信人</label>
                    <div class="col-lg-6">
                        <p class="form-control-static">{{ to_people.nickname }}</p>
                    </div>
                </div>
                <div class="form-group">
                    <label for="content" class="col-lg-2 control-label">私信内容</label>
                    <div class="col-lg-6">
                        {{ chat_form.content(class_='form-control', rows=6, id='content', placeholder='请输入私信内容……') }}
                    </div>
                    <div class="col-lg-4">
                        <p class="text-danger">{{ ', '.join(chat_form.content.errors) }}</p>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-6">
                        {{ chat_form.submit(class_='btn btn-primary') }}
                    </div>
                </div>
                {{ chat_form.hidden_tag() }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

microblog/themes/newstyle/templates/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p class="text-center">{{ message }}</p>
    </div>
    {% endfor %}
    {% endif %}
{% endwith %}

microblog/themes/newstyle/templates/header.html
<header>
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
            <span class="sr-only">导航</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('frontend.index') }}">VIEBOO</a>
    </div>

    <div class="collapse navbar-collapse" id="navigation">
        <ul class="nav navbar-nav">
            <li{%- if active == 'index' %} class="active"{% endif -%}><a href="{{ url_for('frontend.index') }}">首页</a></li>
            <li{%- if active == 'square' %} class="active"{% endif -%}><a href="{{ url_for('frontend.square') }}">微博广场</a></li>
            {% if g.user.is_authenticated -%}
            <li{%- if active == 'people' %} class="active"{% endif -%}><a href="{{ url_for('frontend.people', id=g.user.id) }}">个人主页</a></li>
            <li{%- if active == 'album' %} class="active"{% endif -%}><a href="{{ url_for('frontend.album', id=g.user.id) }}">相册</a></li>
            <li class="dropdown{%- if active == 'profile' %} active{% endif -%}">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        个人资料 <b class="caret"></b>
                    </a>
                <ul class="dropdown-menu">
                    <li><a href="{{ url_for('account.profile') }}">基本资料</a></li>
                    <li><a href="{{ url_for('account.profile_detail') }}">详细资料</a></li>
                    <li><a href="{{ url_for('account.password') }}">修改密码</a></li>
                    <li><a href="{{ url_for('account.avatar') }}">修改头像</a></li>
                </ul>
            </li>
            <li class="dropdown{%- if active == 'friendship' %} active{% endif -%}">
                <a href="" class="dropdown-toggle" data-toggle="dropdown">
                    好友 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{{ url_for('friendship.show_following') }}">我关注的</a></li>
                    <li><a href="{{ url_for('friendship.show_followed') }}">关注我的</a></li>
                    <li><a href="{{ url_for('friendship.show_mutual') }}">互相关注</a></li>
                    <li class="divider"></li>
                    <li><a href="{{ url_for('friendship.show_blocking') }}">黑名单</a></li>
                    <li class="divider"></li>
                    <li><a href="{{ url_for('friendship.show_inbox') }}">私信</a></li>
                </ul>
            </li>
            {% if g.user.is_admin() %}
            <li><a href="{{ url_for('admin.index') }}">管理中心</a></li>
            {% endif %}
            {% endif %}
            <li{%- if active == 'about' %} class="active"{% endif -%}><a href="{{ url_for('frontend.show_about') }}">关于</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if g.user.is_authenticated %}
            <li{%- if active == 'notification' %} class="active"{% endif -%}>
                <a href="{{ url_for('notification.show_notification') }}">
                    通知
                    {% set new_notification_number = g.user.notifications.filter_by(has_read=False).count() %}
                    {% if new_notification_number %}
                    <span class="text-danger">({{ new_notification_number }})</span>
                    {# <span class="glyphicon glyphicon-star" style="color: #CC3333;"></span> #}
                    {% endif %}
                </a>
            </li>
            <li class="dropdown">
                <a href="" class="dropdown-toggle" data-toggle="dropdown">
                    账号 <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="">设置</a></li>
                    <li class="divider"></li>
                    <li><a href="{{ url_for('account.logout') }}">注销</a></li>
                </ul>
            </li>
            {% else %}
            <li><a href="{{ url_for('account.register') }}">注册</a></li>
            {% endif %}
        </ul>
        {% if g.user.is_authenticated %}
        <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
            <input type="text" class="form-control" placeholder="请输入关键字……">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
        </form>
        {% else %}
        <form class="navbar-form navbar-right" role="login" action="{{ url_for('account.login') }}" method="POST">
            <div class="form-group">
                <label for="login" class="sr-only">邮箱</label>
                <input id="login" name="login" type="text" class="form-control" placeholder="邮箱">
            </div>
            <div class="form-group">
                <label for="password" class="sr-only">密码</label>
                <input id="password" name="password" type="password" class="form-control" placeholder="密码">
            </div>
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <button type="submit" class="btn btn-default">登录</button>
        </form>
        {% endif %}
    </div>
</nav>
</header>

microblog/themes/newstyle/templates/notification.html
{% extends theme('layout.html') %}
{% set active = 'notification' %}
{% block title %}通知{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <ul>
                {% for notification in notifications %}
                {% if notification.__repr__() %}
                <li class="list-group-item{{ ' text-muted' if notification.has_read }}">
                    <span class="glyphicon glyphicon-arrow-right"></span>
                    {{ notification | safe }}&emsp;&emsp;<span class="text-muted"><small>{{ notification.create_time }}</small></span>
                    <a href="{{ url_for('notification.delete_notification', id=notification.id) }}" class="btn btn-xs btn-default pull-right">删除</a>
                    <span class="pull-right">&nbsp;</span>
                    {% if not notification.has_read %}
                    <a href="{{ url_for('notification.set_read', id=notification.id) }}" class="btn btn-xs btn-danger pull-right">标记为已读</a>
                    {% else %}
                    <a href="{{ url_for('notification.set_unread', id=notification.id) }}" class="btn btn-xs btn-default pull-right">标记为未读</a>
                    {% endif %}
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}